%Simulates the inlays, non-inlays, and remaining body of the pendulum

function o = yukawaAnglePendulumCore(position, lambda, theta, j1, w1, a1, thickness1, ph, pl, d)

	o = ...
	ph * yukawaAngleCore( lambda, theta,    j1, w1/2, a1)   .* ( exp( -( position                 	+d)' * (1./lambda )) ) + ...
	ph * yukawaAngleCore( lambda, theta, -w1/2,  -j1, a1)   .* ( exp( -( position + thickness1 - a1 +d)' * (1./lambda )) ) + ... 
	pl * yukawaAngleCore( lambda, theta, -w1/2,  -j1, a1)   .* ( exp( -( position                   +d)' * (1./lambda )) ) + ...
	pl * yukawaAngleCore( lambda, theta,    j1, w1/2, a1)   .* ( exp( -( position + thickness1 - a1 +d)' * (1./lambda )) ) + ... 
        pl * yukawaAngleCore( lambda, theta, -w1/2, w1/2, thickness1 - 2*a1) ...
							        .* ( exp( -( position + a1              +d)' * (1./lambda )) ) + ...
        0;
end
