include ../../../Makefile.inc

plots:
	 gnuplot -e "filename = 'shortStrokeoHHist.dat'; plotTitle = 'Short stroke oH Histogram'; bottomlabel = 'torque difference (N-m)'"  $(HOMEDIR)/glib/stockHistogram.gpl


clean:
	-rm *.eps 
