include ../../../Makefile.inc

plots:
	 gnuplot -e "filename = 'shortStrokeo0Hist.dat'; plotTitle = 'Short stroke o0 Histogram'; bottomlabel = 'torque difference (N-m)'"  $(HOMEDIR)/glib/stockHistogram.gpl


clean:
	-rm *.eps 
